//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mellis.Lang.Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized_Base_Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_Base_Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mellis.Lang.Base.Resources.Localized_Base_Entities", typeof(Localized_Base_Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att hämta värde från typen &apos;{0}&apos; via indexering..
        /// </summary>
        public static string Ex_Base_IndexGet {
            get {
                return ResourceManager.GetString("Ex_Base_IndexGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att sätta värde på typen &apos;{0}&apos; via indexering..
        /// </summary>
        public static string Ex_Base_IndexSet {
            get {
                return ResourceManager.GetString("Ex_Base_IndexSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; kan inte köras som en funktion..
        /// </summary>
        public static string Ex_Base_Invoke {
            get {
                return ResourceManager.GetString("Ex_Base_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; stödjer inte &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Base_Operator {
            get {
                return ResourceManager.GetString("Ex_Base_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; stödjer inte &apos;{2}&apos; med typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Base_OperatorInvalidType {
            get {
                return ResourceManager.GetString("Ex_Base_OperatorInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att hämta egenskap från typen &apos;{0}&apos;..
        /// </summary>
        public static string Ex_Base_PropertyGet {
            get {
                return ResourceManager.GetString("Ex_Base_PropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att sätta egenskap på typen &apos;{0}&apos;..
        /// </summary>
        public static string Ex_Base_PropertySet {
            get {
                return ResourceManager.GetString("Ex_Base_PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett {1} boolean värde kan inte adderas med ett annat värde..
        /// </summary>
        public static string Ex_Boolean_AddInvalidOperation {
            get {
                return ResourceManager.GetString("Ex_Boolean_AddInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett {1} boolean värde kan inte divideras med ett annat värde..
        /// </summary>
        public static string Ex_Boolean_DivideInvalidOperation {
            get {
                return ResourceManager.GetString("Ex_Boolean_DivideInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett {1} boolean värde kan inte indexeras..
        /// </summary>
        public static string Ex_Boolean_IndexGet {
            get {
                return ResourceManager.GetString("Ex_Boolean_IndexGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att sätta inre värde på ett {1} boolean värde genom indexering..
        /// </summary>
        public static string Ex_Boolean_IndexSet {
            get {
                return ResourceManager.GetString("Ex_Boolean_IndexSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett {1} boolean värde kan inte köras som en funktion..
        /// </summary>
        public static string Ex_Boolean_Invoke {
            get {
                return ResourceManager.GetString("Ex_Boolean_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett {1} boolean värde kan inte multipliseras med ett annat värde..
        /// </summary>
        public static string Ex_Boolean_MultiplyInvalidOperation {
            get {
                return ResourceManager.GetString("Ex_Boolean_MultiplyInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att läsa egenskapen &apos;{2}&apos; från ett {1} boolean värde. Booleans har inga egenskaper..
        /// </summary>
        public static string Ex_Boolean_PropertyGet {
            get {
                return ResourceManager.GetString("Ex_Boolean_PropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att ändra egenskapen &apos;{2}&apos; på ett {1} boolean värde. Booleans har inga egenskaper..
        /// </summary>
        public static string Ex_Boolean_PropertySet {
            get {
                return ResourceManager.GetString("Ex_Boolean_PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett {1} boolean värde kan inte subtraheras med ett annat värde..
        /// </summary>
        public static string Ex_Boolean_SubtractInvalidOperation {
            get {
                return ResourceManager.GetString("Ex_Boolean_SubtractInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att addera decimaltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Double_AddInvalidType {
            get {
                return ResourceManager.GetString("Ex_Double_AddInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att dividera decimaltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Double_DivideInvalidType {
            get {
                return ResourceManager.GetString("Ex_Double_DivideInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett decimaltal kan inte indexeras..
        /// </summary>
        public static string Ex_Double_IndexGet {
            get {
                return ResourceManager.GetString("Ex_Double_IndexGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att sätta inre värde på ett decimaltal genom indexering..
        /// </summary>
        public static string Ex_Double_IndexSet {
            get {
                return ResourceManager.GetString("Ex_Double_IndexSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett decimaltal kan inte köras som en funktion..
        /// </summary>
        public static string Ex_Double_Invoke {
            get {
                return ResourceManager.GetString("Ex_Double_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att multiplisera decimaltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Double_MultiplyInvalidType {
            get {
                return ResourceManager.GetString("Ex_Double_MultiplyInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att läsa egenskapen &apos;{1}&apos; från decimaltalet. Decimaltal har inga egenskaper..
        /// </summary>
        public static string Ex_Double_PropertyGet {
            get {
                return ResourceManager.GetString("Ex_Double_PropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att ändra egenskapen &apos;{1}&apos; på decimaltalet. Decimaltal har inga egenskaper..
        /// </summary>
        public static string Ex_Double_PropertySet {
            get {
                return ResourceManager.GetString("Ex_Double_PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att subtrahera decimaltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Double_SubtractInvalidType {
            get {
                return ResourceManager.GetString("Ex_Double_SubtractInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att addera heltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Int_AddInvalidType {
            get {
                return ResourceManager.GetString("Ex_Int_AddInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att dividera heltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Int_DivideInvalidType {
            get {
                return ResourceManager.GetString("Ex_Int_DivideInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett heltal kan inte indexeras..
        /// </summary>
        public static string Ex_Int_IndexGet {
            get {
                return ResourceManager.GetString("Ex_Int_IndexGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att sätta inre värde på ett heltal genom indexering..
        /// </summary>
        public static string Ex_Int_IndexSet {
            get {
                return ResourceManager.GetString("Ex_Int_IndexSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett heltalsvärde kan inte köras som en funktion..
        /// </summary>
        public static string Ex_Int_Invoke {
            get {
                return ResourceManager.GetString("Ex_Int_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att multiplisera heltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Int_MultiplyInvalidType {
            get {
                return ResourceManager.GetString("Ex_Int_MultiplyInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att läsa egenskapen &apos;{1}&apos; från heltalet. Heltal har inga egenskaper..
        /// </summary>
        public static string Ex_Int_PropertyGet {
            get {
                return ResourceManager.GetString("Ex_Int_PropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att ändra egenskapen &apos;{1}&apos; på ett heltal. Heltal har inga egenskaper..
        /// </summary>
        public static string Ex_Int_PropertySet {
            get {
                return ResourceManager.GetString("Ex_Int_PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att subtrahera heltalet &apos;{0}&apos; med värde av typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Int_SubtractInvalidType {
            get {
                return ResourceManager.GetString("Ex_Int_SubtractInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du får inte dela ett tal på noll!.
        /// </summary>
        public static string Ex_Math_DivideByZero {
            get {
                return ResourceManager.GetString("Ex_Math_DivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att addera din textsträng på {1} karaktärer med värde av typen &apos;{2}&apos;..
        /// </summary>
        public static string Ex_String_AddInvalidType {
            get {
                return ResourceManager.GetString("Ex_String_AddInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En textsträng kan inte divideras med ett annat värde..
        /// </summary>
        public static string Ex_String_DivideInvalidOperation {
            get {
                return ResourceManager.GetString("Ex_String_DivideInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En textsträng kan endast indexeras av heltal, inte av typen &apos;{2}&apos;..
        /// </summary>
        public static string Ex_String_IndexGet_InvalidType {
            get {
                return ResourceManager.GetString("Ex_String_IndexGet_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att läsa bokstaven på plats &apos;{2}&apos; då den är utanför textsträngens längd ({1})..
        /// </summary>
        public static string Ex_String_IndexGet_OutOfRange {
            get {
                return ResourceManager.GetString("Ex_String_IndexGet_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att ändra enstaka bokstäver i en textsträng genom indexering..
        /// </summary>
        public static string Ex_String_IndexSet {
            get {
                return ResourceManager.GetString("Ex_String_IndexSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En textsträng kan inte köras som en funktion..
        /// </summary>
        public static string Ex_String_Invoke {
            get {
                return ResourceManager.GetString("Ex_String_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En textsträng kan inte multipliseras med ett annat värde..
        /// </summary>
        public static string Ex_String_MultiplyInvalidOperation {
            get {
                return ResourceManager.GetString("Ex_String_MultiplyInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att läsa egenskapen &apos;{2}&apos; från textsträngen..
        /// </summary>
        public static string Ex_String_PropertyGet {
            get {
                return ResourceManager.GetString("Ex_String_PropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att ändra egenskapen &apos;{2}&apos; på en textsträng..
        /// </summary>
        public static string Ex_String_PropertySet {
            get {
                return ResourceManager.GetString("Ex_String_PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En textsträng kan inte subtraheras med ett annat värde..
        /// </summary>
        public static string Ex_String_SubtractInvalidOperation {
            get {
                return ResourceManager.GetString("Ex_String_SubtractInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falskt.
        /// </summary>
        public static string Type_Boolean_False {
            get {
                return ResourceManager.GetString("Type_Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean.
        /// </summary>
        public static string Type_Boolean_Name {
            get {
                return ResourceManager.GetString("Type_Boolean_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sant.
        /// </summary>
        public static string Type_Boolean_True {
            get {
                return ResourceManager.GetString("Type_Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimaltal.
        /// </summary>
        public static string Type_Double_Name {
            get {
                return ResourceManager.GetString("Type_Double_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to funktion.
        /// </summary>
        public static string Type_Function_Name {
            get {
                return ResourceManager.GetString("Type_Function_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heltal.
        /// </summary>
        public static string Type_Int_Name {
            get {
                return ResourceManager.GetString("Type_Int_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textsträng.
        /// </summary>
        public static string Type_String_Name {
            get {
                return ResourceManager.GetString("Type_String_Name", resourceCulture);
            }
        }
    }
}
