//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mellis.Lang.Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized_Base_Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_Base_Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mellis.Lang.Base.Resources.Localized_Base_Entities", typeof(Localized_Base_Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att hämta värde från typen &apos;{0}&apos; via indexering..
        /// </summary>
        public static string Ex_Base_IndexGet {
            get {
                return ResourceManager.GetString("Ex_Base_IndexGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att sätta värde på typen &apos;{0}&apos; via indexering..
        /// </summary>
        public static string Ex_Base_IndexSet {
            get {
                return ResourceManager.GetString("Ex_Base_IndexSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; kan inte köras som en funktion..
        /// </summary>
        public static string Ex_Base_Invoke {
            get {
                return ResourceManager.GetString("Ex_Base_Invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; har inte stöd att genomsökas..
        /// </summary>
        public static string Ex_Base_MemberIn {
            get {
                return ResourceManager.GetString("Ex_Base_MemberIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; stödjer inte &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Base_Operator {
            get {
                return ResourceManager.GetString("Ex_Base_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; stödjer inte &apos;{2}&apos; med typen &apos;{1}&apos;..
        /// </summary>
        public static string Ex_Base_OperatorInvalidType {
            get {
                return ResourceManager.GetString("Ex_Base_OperatorInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att hämta egenskap från typen &apos;{0}&apos;..
        /// </summary>
        public static string Ex_Base_PropertyGet {
            get {
                return ResourceManager.GetString("Ex_Base_PropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Går inte att sätta egenskap på typen &apos;{0}&apos;..
        /// </summary>
        public static string Ex_Base_PropertySet {
            get {
                return ResourceManager.GetString("Ex_Base_PropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det går inte att dela ett tal på noll!.
        /// </summary>
        public static string Ex_Math_DivideByZero {
            get {
                return ResourceManager.GetString("Ex_Math_DivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En textsträng kan endast indexeras av heltal, inte av typen &apos;{2}&apos;..
        /// </summary>
        public static string Ex_String_IndexGet_InvalidType {
            get {
                return ResourceManager.GetString("Ex_String_IndexGet_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gick inte att läsa bokstaven på plats &apos;{2}&apos; då den är utanför textsträngens längd ({1})..
        /// </summary>
        public static string Ex_String_IndexGet_OutOfRange {
            get {
                return ResourceManager.GetString("Ex_String_IndexGet_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falskt.
        /// </summary>
        public static string Type_Boolean_False {
            get {
                return ResourceManager.GetString("Type_Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boolean.
        /// </summary>
        public static string Type_Boolean_Name {
            get {
                return ResourceManager.GetString("Type_Boolean_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sant.
        /// </summary>
        public static string Type_Boolean_True {
            get {
                return ResourceManager.GetString("Type_Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbyggd funktion.
        /// </summary>
        public static string Type_ClrFunction_Name {
            get {
                return ResourceManager.GetString("Type_ClrFunction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;inbyggd funktion &apos;{0}&apos;&gt;.
        /// </summary>
        public static string Type_ClrFunction_ToString {
            get {
                return ResourceManager.GetString("Type_ClrFunction_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimaltal.
        /// </summary>
        public static string Type_Double_Name {
            get {
                return ResourceManager.GetString("Type_Double_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inte-ett-tal.
        /// </summary>
        public static string Type_Double_NaN {
            get {
                return ResourceManager.GetString("Type_Double_NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -∞.
        /// </summary>
        public static string Type_Double_NegInfinity {
            get {
                return ResourceManager.GetString("Type_Double_NegInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∞.
        /// </summary>
        public static string Type_Double_PosInfinity {
            get {
                return ResourceManager.GetString("Type_Double_PosInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heltal.
        /// </summary>
        public static string Type_Int_Name {
            get {
                return ResourceManager.GetString("Type_Int_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intet.
        /// </summary>
        public static string Type_Null_Name {
            get {
                return ResourceManager.GetString("Type_Null_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textsträng.
        /// </summary>
        public static string Type_String_Name {
            get {
                return ResourceManager.GetString("Type_String_Name", resourceCulture);
            }
        }
    }
}
