//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mellis.Lang.Python3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized_Python3_Parser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_Python3_Parser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mellis.Lang.Python3.Resources.Localized_Python3_Parser", typeof(Localized_Python3_Parser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på värdet i koden..
        /// </summary>
        internal static string Ex_Literal_Format {
            get {
                return ResourceManager.GetString("Ex_Literal_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar en &apos;{4}&apos; som slutparantes..
        /// </summary>
        internal static string Ex_Parenthesis_NoClosing {
            get {
                return ResourceManager.GetString("Ex_Parenthesis_NoClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte skriva över betydelsen för &apos;{0}&apos;..
        /// </summary>
        internal static string Ex_Syntax_Assign_Boolean {
            get {
                return ResourceManager.GetString("Ex_Syntax_Assign_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte sätta värdet på ett uttryck..
        /// </summary>
        internal static string Ex_Syntax_Assign_Expression {
            get {
                return ResourceManager.GetString("Ex_Syntax_Assign_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte sätta värdet på faktiskt &apos;{0}&apos; värde..
        /// </summary>
        internal static string Ex_Syntax_Assign_Literal {
            get {
                return ResourceManager.GetString("Ex_Syntax_Assign_Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte skriva över betydelsen för &apos;intet&apos;..
        /// </summary>
        internal static string Ex_Syntax_Assign_None {
            get {
                return ResourceManager.GetString("Ex_Syntax_Assign_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förväntar en regel men det var tomt efter &apos;{4}&apos;..
        /// </summary>
        internal static string Ex_Syntax_ExpectedChild {
            get {
                return ResourceManager.GetString("Ex_Syntax_ExpectedChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar ett kolon i slutet av din &apos;else&apos; i din &apos;for&apos;-loop..
        /// </summary>
        internal static string Ex_Syntax_For_Else_MissingColon {
            get {
                return ResourceManager.GetString("Ex_Syntax_For_Else_MissingColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar ett kolon i slutet av din &apos;for&apos;-loop..
        /// </summary>
        internal static string Ex_Syntax_For_MissingColon {
            get {
                return ResourceManager.GetString("Ex_Syntax_For_MissingColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar ett kolon i slutet av villkoret efter din &apos;elif&apos;..
        /// </summary>
        internal static string Ex_Syntax_If_Elif_MissingColon {
            get {
                return ResourceManager.GetString("Ex_Syntax_If_Elif_MissingColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar ett kolon i slutet av din &apos;else&apos; i din &apos;if&apos;-sats..
        /// </summary>
        internal static string Ex_Syntax_If_Else_MissingColon {
            get {
                return ResourceManager.GetString("Ex_Syntax_If_Else_MissingColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar ett kolon efter villkoret i slutet av din &apos;if&apos;-sats..
        /// </summary>
        internal static string Ex_Syntax_If_MissingColon {
            get {
                return ResourceManager.GetString("Ex_Syntax_If_MissingColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användning av &apos;{4}&apos; stödjs inte än..
        /// </summary>
        internal static string Ex_Syntax_NotYetImplemented_Keyword {
            get {
                return ResourceManager.GetString("Ex_Syntax_NotYetImplemented_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oförväntad regel av typ &apos;{5}&apos; i en &apos;{4}&apos;..
        /// </summary>
        internal static string Ex_Syntax_UnexpectedChildType {
            get {
                return ResourceManager.GetString("Ex_Syntax_UnexpectedChildType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar ett kolon i slutet av din &apos;else&apos; i din &apos;while&apos;-loop..
        /// </summary>
        internal static string Ex_Syntax_While_Else_MissingColon {
            get {
                return ResourceManager.GetString("Ex_Syntax_While_Else_MissingColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saknar ett kolon i slutet av din &apos;while&apos;-loop..
        /// </summary>
        internal static string Ex_Syntax_While_MissingColon {
            get {
                return ResourceManager.GetString("Ex_Syntax_While_MissingColon", resourceCulture);
            }
        }
    }
}
