//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mellis.Lang.Python3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized_Python3_Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized_Python3_Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mellis.Lang.Python3.Resources.Localized_Python3_Entities", typeof(Localized_Python3_Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; kan inte itereras..
        /// </summary>
        internal static string Builtin_Iter_Arg1_NotIterable {
            get {
                return ResourceManager.GetString("Builtin_Iter_Arg1_NotIterable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktionen &apos;iter&apos; har inte stöd för 2st argument än..
        /// </summary>
        internal static string Builtin_Iter_Arg2_NotYetImplemented {
            get {
                return ResourceManager.GetString("Builtin_Iter_Arg2_NotYetImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typen &apos;{0}&apos; är inte en iterator..
        /// </summary>
        internal static string Builtin_Next_Arg1_NotIterator {
            get {
                return ResourceManager.GetString("Builtin_Next_Arg1_NotIterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteratorn har tagit slut..
        /// </summary>
        internal static string Builtin_Next_StopIteration {
            get {
                return ResourceManager.GetString("Builtin_Next_StopIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteratorn &apos;{0}&apos; har tagit slut..
        /// </summary>
        internal static string Builtin_Next_StopIteration_Named {
            get {
                return ResourceManager.GetString("Builtin_Next_StopIteration_Named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;float()&apos; omvandla en tom text sträng till decimaltal..
        /// </summary>
        internal static string Ex_DoubleType_Ctor_Arg1_EmptyString {
            get {
                return ResourceManager.GetString("Ex_DoubleType_Ctor_Arg1_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;float()&apos; omvandla följande text sträng till decimaltal: {0}.
        /// </summary>
        internal static string Ex_DoubleType_Ctor_Arg1_InvalidString {
            get {
                return ResourceManager.GetString("Ex_DoubleType_Ctor_Arg1_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Första värdet till &apos;float()&apos; måste vara en text sträng, nummer eller boolean..
        /// </summary>
        internal static string Ex_DoubleType_Ctor_Arg1_Type {
            get {
                return ResourceManager.GetString("Ex_DoubleType_Ctor_Arg1_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;int()&apos; omvandla en tom text sträng till heltal..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg1_EmptyString {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg1_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;int()&apos; omvandla följande text sträng till heltal: {0}.
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg1_InvalidString {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg1_InvalidString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;int()&apos; omvandla värdetypen &apos;inte-ett-tal&apos; till heltal..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg1_NaN {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg1_NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;int()&apos; omvandla -∞ till heltal..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg1_NegInf {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg1_NegInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Första värdet till &apos;int()&apos; måste vara en text sträng och inte av typen &apos;{0}&apos; när du även ger talbas som andra värde..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg1_NotString_Arg2_Int {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg1_NotString_Arg2_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;int()&apos; omvandla ∞ till heltal..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg1_PosInf {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg1_PosInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Första värdet till &apos;int()&apos; måste vara en text sträng, nummer eller boolean..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg1_Type {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg1_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talbasen som andra värde till `int()` måste vara 0 eller mellan 2 och 36..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg2_OutOfRange {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg2_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talbasen som andra värde till &apos;int()&apos; måste vara ett heltal, inte &apos;{0}&apos;..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_Arg2_Type {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_Arg2_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;int()&apos; omvandla följande decimaltal till heltal: {0}. Heltal måste vara mindre än 2 147 483 647 och större än -2 147 483 648..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_DoubleOutOfBounds {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_DoubleOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan inte i &apos;int()&apos; omvandla följande textsträng till heltal:: {0}. Heltal måste vara mindre än 2 147 483 647 och större än -2 147 483 648..
        /// </summary>
        internal static string Ex_IntegerType_Ctor_StringOutOfBounds {
            get {
                return ResourceManager.GetString("Ex_IntegerType_Ctor_StringOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iterator.
        /// </summary>
        internal static string Type_Enumerator_Name {
            get {
                return ResourceManager.GetString("Type_Enumerator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;iterator för klass &apos;{0}&apos;&gt;.
        /// </summary>
        internal static string Type_Enumerator_ToString {
            get {
                return ResourceManager.GetString("Type_Enumerator_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spann.
        /// </summary>
        internal static string Type_Range_Name {
            get {
                return ResourceManager.GetString("Type_Range_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typ.
        /// </summary>
        internal static string Type_Type_Name {
            get {
                return ResourceManager.GetString("Type_Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;klass &apos;{0}&apos;&gt;.
        /// </summary>
        internal static string Type_Type_ToString {
            get {
                return ResourceManager.GetString("Type_Type_ToString", resourceCulture);
            }
        }
    }
}
